apiVersion: v1
kind: Secret
metadata:
  name: archive-ledger-secret
type: Opaque
stringData:
  ARCHIVE_LEDGER_DB_USERNAME: archive_ledger
  ARCHIVE_LEDGER_DB_PASSWORD: replace-with-local-or-cluster-secret
